name             'magic'
maintainer       'Texas A&M'
maintainer_email 'jarosser06@arch.tamu.edu'
license          'MIT'
description      'Installs/Configures magic'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'nginx'
depends          'git'
supports         'ubuntu', '>= 12.04'
supports         'centos', '>= 6.4'
